export const categoryConstants = {
	GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
	GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
	ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
	ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
	ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE'
};
